name: News Home Reader CI

on:
  push:
    branches: [ "main" ]
#    paths:
#      - 'library/**'
#      - 'gradle/**'
#      - '*.kts'

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # macOS ist für KMP am stabilsten (auch wenn du noch kein iOS hast)
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Checkout News Reader
        uses: actions/checkout@v4
        with:
          path: News-Home-Reader

      - name: Checkout Library
        uses: actions/checkout@v4
        with:
          repository: sknull/Stephans-KMP-Components
          path: Stephans-KMP-Components
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Aktiviert den Schreibzugriff auf den Cache auch für Pull Requests
          cache-read-only: false
          # Hilft dabei, Snapshots (wie deine essence lib) besser zu cachen
          cache-encryption-key: ${{ secrets.Gradle_Encryption_Key }}

      - name: Run Tests
        working-directory: News-Home-Reader
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_ACTOR: sknull
        run: |
          chmod +x gradlew
          ./gradlew clean test jvmTest --no-configuration-cache

      - name: Build Artifacts
        working-directory: News-Home-Reader
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_ACTOR: sknull
        run: |
          chmod +x gradlew
          ./gradlew zip assembleDebug

      - name: Upload Desktop App
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-App-Zip
          path: News-Home-Reader/composeApp/build/distributions/*.zip

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-Debug-APK
          path: News-Home-Reader/composeApp/build/outputs/apk/debug/*.apk

      - name: Upload Aciidoc
        uses: actions/upload-artifact@v4
        with:
          name: Asciidoc-PDF
          path: News-Home-Reader/composeApp/build/asciidoc/*.pdf
